/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpisodesRouteImport } from './routes/episodes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SlugIdRouteImport } from './routes/$slug/$id'
import { Route as PlayerEpisodeIdRouteImport } from './routes/player.$episodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodesRoute = EpisodesRouteImport.update({
  id: '/episodes',
  path: '/episodes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIdRoute = SlugIdRouteImport.update({
  id: '/$slug/$id',
  path: '/$slug/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerEpisodeIdRoute = PlayerEpisodeIdRouteImport.update({
  id: '/player/$episodeId',
  path: '/player/$episodeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/episodes': typeof EpisodesRoute
  '/settings': typeof SettingsRoute
  '/$slug/$id': typeof SlugIdRoute
  '/player/$episodeId': typeof PlayerEpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/episodes': typeof EpisodesRoute
  '/settings': typeof SettingsRoute
  '/$slug/$id': typeof SlugIdRoute
  '/player/$episodeId': typeof PlayerEpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/episodes': typeof EpisodesRoute
  '/settings': typeof SettingsRoute
  '/$slug/$id': typeof SlugIdRoute
  '/player/$episodeId': typeof PlayerEpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/episodes' | '/settings' | '/$slug/$id' | '/player/$episodeId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/episodes' | '/settings' | '/$slug/$id' | '/player/$episodeId'
  id:
    | '__root__'
    | '/'
    | '/episodes'
    | '/settings'
    | '/$slug/$id'
    | '/player/$episodeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpisodesRoute: typeof EpisodesRoute
  SettingsRoute: typeof SettingsRoute
  SlugIdRoute: typeof SlugIdRoute
  PlayerEpisodeIdRoute: typeof PlayerEpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episodes': {
      id: '/episodes'
      path: '/episodes'
      fullPath: '/episodes'
      preLoaderRoute: typeof EpisodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/$id': {
      id: '/$slug/$id'
      path: '/$slug/$id'
      fullPath: '/$slug/$id'
      preLoaderRoute: typeof SlugIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player/$episodeId': {
      id: '/player/$episodeId'
      path: '/player/$episodeId'
      fullPath: '/player/$episodeId'
      preLoaderRoute: typeof PlayerEpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpisodesRoute: EpisodesRoute,
  SettingsRoute: SettingsRoute,
  SlugIdRoute: SlugIdRoute,
  PlayerEpisodeIdRoute: PlayerEpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
